camera:
  - platform: generic
    still_image_url: !secret camera_image_url
    stream_source: !secret camera_stream_url
    username: !secret camera_username
    password: !secret camera_password

  - platform: mjpeg
    name: OctoPrint
    still_image_url: !secret octoprint_camera_image_url
    mjpeg_url: !secret octoprint_camera_stream_url