influxdb:
  host: !secret influxdb_url
  database: !secret influxdb_db
  include:
    entities:
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature
      - sensor.hue_motion_sensor_1_light_level
      - sensor.hue_motion_sensor_1_temperature
      - sensor.hue_motion_sensor_2_light_level
      - sensor.hue_motion_sensor_2_temperature
      - sensor.energy_01_wattage
      - sensor.energy_01_total_daily_energy
      - sensor.energy_02_wattage
      - sensor.energy_02_total_daily_energy
      - sensor.energy_03_wattage
      - sensor.energy_03_total_daily_energy
      - sensor.energy_04_wattage
      - sensor.energy_04_total_daily_energy
      - sensor.zwave_energy_01_wattage
      - sensor.zwave_energy_01_total_daily_energy
      - sensor.zwave_energy_02_wattage
      - sensor.zwave_energy_02_total_daily_energy
      - sensor.zwave_energy_03_wattage
      - sensor.zwave_energy_03_total_daily_energy
      - sensor.zwave_energy_04_wattage
      - sensor.zwave_energy_04_total_daily_energy
      - sensor.zwave_energy_05_wattage
      - sensor.zwave_energy_05_total_daily_energy
      - sensor.temperature_reader_01_temperature
      - sensor.temperature_reader_02_temperature
      - sensor.temperature_reader_03_temperature
      - sensor.temperature_reader_04_temperature
      - sensor.temperature_reader_05_temperature
      - sensor.temperature_reader_02_06_temperature
      - sensor.temperature_reader_02_07_temperature
      - sensor.temperature_reader_02_08_temperature
      - sensor.temperature_reader_09_temperature
      - sensor.temperature_reader_01_humidity
      - sensor.temperature_reader_02_humidity
      - sensor.temperature_reader_03_humidity
      - sensor.temperature_reader_04_humidity
      - sensor.temperature_reader_05_humidity
      - sensor.temperature_reader_02_06_humidity
      - sensor.temperature_reader_02_07_humidity
      - sensor.temperature_reader_02_08_humidity
      - sensor.temperature_reader_09_humidity
      - sensor.pv_voltage
      - sensor.pv_voltage_a
      - sensor.pv_current_a
      - sensor.nedis_smart_plug_current
      - sensor.nedis_smart_plug_current_consumption
      - sensor.nedis_smart_plug_voltage
      - sensor.nedis_smart_plug_current_consumption_cost
      - sensor.nedis_smart_plug_consumption_kwh