- action:
  - data:
      entity_id: input_boolean.washingmachine_busy
    service: input_boolean.turn_on
  alias: Wasmachine - bezig
  condition: []
  id: '1503836316200'
  trigger:
  - above: '2'
    entity_id: sensor.greenwave_1_power
    platform: numeric_state
- action:
  - data:
      message: Ik ben klaar!
      title: 'Wasmachine: '
    service: notify.ios_iphonesjors
  - data:
      message: Ik ben klaar!
      title: 'Wasmachine: '
    service: notify.ios_iphonesaskia
  alias: Wasmachine - notificatie
  condition: []
  id: '1504637423321'
  trigger:
  - entity_id: input_boolean.washingmachine_busy
    for:
      minutes: 10
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: input_boolean.dryer_busy
    service: input_boolean.turn_on
  alias: Droger - bezig
  condition: []
  id: '1504637665698'
  trigger:
  - above: '2'
    entity_id: sensor.greenwave_2_power
    platform: numeric_state
- action:
  - data:
      message: Ik ben klaar!
      title: 'Droger: '
    service: notify.ios_iphonesjors
  - data:
      message: Ik ben klaar!
      title: 'Droger: '
    service: notify.ios_iphonesaskia
  alias: Droger - notificatie
  condition: []
  id: '1504637782718'
  trigger:
  - entity_id: input_boolean.dryer_busy
    for:
      minutes: 10
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: input_boolean.dryer_busy
    service: input_boolean.turn_off
  alias: Droger - klaar
  condition: []
  id: '1504637906269'
  trigger:
  - below: '1.5'
    entity_id: sensor.greenwave_2_power
    platform: numeric_state
- action:
  - data:
      entity_id: input_boolean.washingmachine_busy
    service: input_boolean.turn_off
  alias: Wasmachine - klaar
  condition: []
  id: '1504638156210'
  trigger:
  - below: '5'
    entity_id: sensor.greenwave_1_power
    platform: numeric_state
- action:
  - data:
      entity_id: light.hue_color_lamp_1
    service: light.turn_off
  alias: Woonkamer - Uit om 01:00
  condition:
  - condition: state
    entity_id: input_boolean.auto_livingroom_lights_off
    state: 'on'
  id: '1504638451610'
  trigger:
  - at: 01:00:00
    platform: time
- action:
  - data:
      entity_id: light.hue_color_lamp_1
    service: light.turn_on
  alias: Woonkamer - Aan na zonsondergang en/of na 17:00
  condition:
  - condition: state
    entity_id: input_boolean.auto_livingroom_lights_on
    state: 'on'
  - after: '17:00'
    condition: time
  id: '1504638716665'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      message: request_location_update
    service: notify.ios_iphonesjors
  - data:
      message: request_location_update
    service: notify.ios_iphonesaskia
  alias: Location - Update
  condition: []
  id: '1504639482098'
  trigger:
    platform: time
    minutes: /15
    seconds: 0
- action: []
  alias: Televisie - Uit om 01:00
  condition:
  - condition: state
    entity_id: input_boolean.auto_television_off
    state: 'on'
  id: '1504639830763'
  trigger:
  - at: 01:00
    platform: time
- action: []
  alias: Televisie - Aan
  condition:
  - condition: state
    entity_id: input_boolean.auto_television_on
    state: 'on'
  - condition: or
    conditions:
    - after: 06:00:00
      condition: time
      weekday:
      - wed
      - thu
      - sat
      - sun
    - after: '17:00:00'
      condition: time
      weekday:
      - mon
      - tue
      - fri
  id: '1504639947771'
  trigger:
  - at: 06:00:00
    platform: time
  - at: '17:00:00'
    platform: time
