homeassistant:
  customize: !include config/customize.yaml

frontend:
  javascript_version: latest

lovelace:

breaking_changes:

config:

system_health:

ios:
  push:
    categories:
      - name: Afvalwijzer
        identifier: 'afvalwijzer'
        actions:
          - identifier: 'MARK_TRASH_MOVED'
            title: 'Okay'
            # activationMode: 'background'
            # authenticationRequired: true
            # destructive: true
            # behavior: 'default'

cloud:

tts:
  - platform: google_translate
    service_name: google_say
    language: 'nl'

history:
  include:
    domains:
      - sensor
      - switch
      - light
      - binary_sensor
      # - cover
  exclude:
    entities:
      - sensor.date
      - sensor.time

# logbook:
#   exclude:
#     domains:
#       - zwave
#     entities:
#       - sensor.time
#       - sensor.date

recorder:
  db_url: !secret database_url

influxdb:
  host: !secret influxdb_url
  database: !secret influxdb_db
  include:
    entities:
      - sensor.vaatwasser_verbruik
      - sensor.tv_verbruik
      - sensor.wasmachine_verbruik
      - sensor.droger_verbruik
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature
      - sensor.multisensor01_brightness
      - sensor.multisensor01_humidity
      - sensor.multisensor01_temperature
      - sensor.multisensor02_brightness
      - sensor.multisensor02_humidity
      - sensor.multisensor02_temperature
      - sensor.multisensor03_brightness
      - sensor.multisensor03_humidity
      - sensor.multisensor03_temperature
      - sensor.power_consumption
      - sensor.power_consumption_low
      - sensor.power_consumption_normal
      - sensor.gas_consumption
      - sensor.hourly_gas_consumption
      - binary_sensor.multisensor01_motion
      - binary_sensor.multisensor02_motion
      - binary_sensor.multisensor03_motion

map:

http:

zwave:
  usb_path: /dev/ttyACM0

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code

sun:

weather:
  - platform: darksky
    api_key: !secret dark_sky

# unifi:
#   controllers:
#     - host: unifi
#       site: Home
#       dont_track_clients: true
#       dont_track_devices: true
#       dont_track_wired_clients: true
#       ssid_filter:
#         - !secret ss_id

automation: !include_dir_merge_list config/automations
binary_sensor: !include config/binary_sensors.yaml
input_boolean: !include config/input_booleans.yaml
input_number: !include config/input_numbers.yaml
# input_select: !include config/input_selects.yaml
light: !include config/lights.yaml
sensor: !include_dir_merge_list config/sensors
switch: !include config/switches.yaml
script: !include config/scripts.yaml