homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include config/customize.yaml

frontend:
  javascript_version: latest

lovelace:

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer/master/custom_updater.json

config:

system_health:

ios:
  push:
    categories:
      - name: Afvalwijzer
        identifier: 'afvalwijzer'
        actions:
          - identifier: 'MARK_TRASH_MOVED'
            title: 'Okay'
            # activationMode: 'background'
            # authenticationRequired: true
            # destructive: true
            # behavior: 'default'

cloud:
  google_actions:
    filter:
      include_domains:
        - switch

tts:
  - platform: google_translate
    service_name: google_say
    language: 'nl'
    base_url: !secret base_url_full

history:
  include:
    domains:
      - sensor
      - switch
      - light
      - binary_sensor
      - cover
  exclude:
    entities:
      - sensor.date
      - sensor.time

logbook:
  exclude:
    domains:
      - zwave
    entities:
      - sensor.time
      - sensor.date

recorder:
  db_url: !secret database_url

influxdb:
  host: !secret influxdb_url
  database: !secret influxdb_db
  include:
    entities:
      - sensor.vaatwasser_verbruik
      - sensor.tv_verbruik
      - sensor.wasmachine_verbruik
      - sensor.droger_verbruik
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature
      - sensor.multisensor01_brightness
      - sensor.multisensor01_humidity
      - sensor.multisensor01_temperature
      - sensor.multisensor02_brightness
      - sensor.multisensor02_humidity
      - sensor.multisensor02_temperature
      - sensor.multisensor03_brightness
      - sensor.multisensor03_humidity
      - sensor.multisensor03_temperature
      - sensor.power_consumption
      - sensor.power_consumption_low
      - sensor.power_consumption_normal
      - sensor.gas_consumption
      - sensor.hourly_gas_consumption
      - binary_sensor.multisensor01_motion
      - binary_sensor.multisensor02_motion
      - binary_sensor.multisensor03_motion

map:

http:
  base_url: !secret base_url

zwave:
  usb_path: /dev/ttyACM0

sun:

weather:
  - platform: darksky
    api_key: !secret dark_sky

automation: !include_dir_merge_list config/automations
binary_sensor: !include config/binary_sensors.yaml
input_boolean: !include config/input_booleans.yaml
# input_select: !include config/input_selects.yaml
light: !include config/lights.yaml
sensor: !include_dir_merge_list config/sensors
switch: !include config/switches.yaml
script: !include config/scripts.yaml

camera:
  platform: generic
  name: Weer
  still_image_url: https://api.buienradar.nl/image/1.0/RadarMapNL?w=480&h=480
  content_type: 'image/gif'
