homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include config/customization.yaml

config:
frontend:
updater:
discovery:
  ignore:
    - plex_mediaserver
    - google_cast
    - sabnzbd
history:
map:
ios:
sun:

recorder:
  db_url: !secret mysql

automation: !include automations.yaml # This location because of automation UI
group: !include config/groups.yaml
input_boolean: !include config/input_booleans.yaml
light: !include config/lights.yaml
sensor: !include_dir_merge_list config/sensors
zone: !include config/zones.yaml
switch: !include config/switches.yaml

mqtt:
  discovery: true

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 3

zwave:
  usb_path: /dev/ttyACM0