homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include config/customization.yaml

config:
frontend:
updater:
discovery:
history:
logbook:
  exclude:
    domains:
      - sun
ios:
sun:

recorder:
  purge_days: 2
  db_url: !secret mysql # mysql://dbuser:password@localhost/dbname

automation: !include_dir_list config/automations
group: !include config/groups.yaml
input_boolean: !include config/input_booleans.yaml
light: !include config/lights.yaml
scene: !include_dir_merge_list config/scenes
script: !include_dir_merge_named config/scripts
sensor: !include_dir_merge_list config/sensors
zone: !include config/zones.yaml

mqtt:

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret ssl_url

zwave:
  usb_path: /dev/ttyUSB-Zwave
