resources:
  - url: /local/lovelace/mini-media-player-bundle.js?v=0.9.4
    type: module
  - url: /local/lovelace/layout-card.js?v=bd7e5a
    type: module
  - url: /local/lovelace/useful-markdown-card.js?v=dfc268
    type: module
  - url: /local/lovelace/compact-custom-header/compact-custom-header.js?v=0.1.6
    type: js
  - url: /local/lovelace/tracker-card.js?v=0.1.5
    type: js

# Compact header
x-compact-header: &compact-header
- type: custom:compact-custom-header
  notification: true
  menu: true
  options: false
  voice: false
  clock: notification
  clock_format: 24
  clock_am_pm: false
  header: true

# Images for Afvalwijzer
x-afval-images: &afval-images
- state_image:
    "gft": /local/afvalwijzer/gft_large.png
    "papier": /local/afvalwijzer/papier_large.png
    "restafval": /local/afvalwijzer/rest_large.png
    "plastic verpakkingsafval": /local/afvalwijzer/plastic_large.png
    "Geen": /local/afvalwijzer/kliko.png

views:
  - title: Home
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            entities:
              - device_tracker.iphonesjors
              - device_tracker.iphone_van_saskia

          - type: light
            entity: light.hue_color_lamp_1

          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: switch.sonoff_4
                tap_action: toggle
              - type: entity-button
                entity: switch.sonoff_2
                tap_action: toggle

          - break

          - type: horizontal-stack
            cards:
              - type: glance
                title: Temperatuur
                entities:
                  - entity: sensor.sensor_zolder__temperatuur
                    name: Zolder
                  - entity: sensor.sensor_slaapkamer_saar__temperatuur
                    name: Saar
              - type: glance
                title: Beweging
                entities:
                  - entity: sensor.sensor_zolder__pir
                    name: Zolder
                  - entity: sensor.sensor_slaapkamer_saar__pir
                    name: Saar

          - type: vertical-stack
            cards:
              - type: glance
                entities:
                  - entity: sensor.wasmachine_verbruik
                    icon: 'mdi:washing-machine'
                  - entity: sensor.droger_verbruik
                    icon: 'mdi:tumble-dryer'
                  - entity: sensor.vaatwasser_verbruik
                    icon: 'mdi:dishwasher'
                  - entity: sensor.tv_verbruik
                    icon: 'mdi:television'

          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: sensor.trash_today
                name: Vandaag
                <<: *afval-images
              - type: picture-entity
                entity: sensor.trash_tomorrow
                name: Morgen
                <<: *afval-images

          - type: custom:useful-markdown-card
            content: >
              Vandaag is het [[ sensor.date_formatted.state ]] nog [[ sensor.trash_days_to_next_pickup.state ]] dagen tot de volgende pickup

          - type: glance
            entities:
              - entity: sensor.trash_gft_formatted
                name: GFT
              - entity: sensor.trash_papier_formatted
                name: Papier
              - entity: sensor.trash_plastic_verpakkingsafval_formatted
                name: Plastic
              - entity: sensor.trash_restafval_formatted
                name: Rest

          - break

          - type: weather-forecast
            entity: weather.dark_sky

          - type: picture-entity
            entity: camera.weer
            aspect_ratio: 16:9

          - <<: *compact-header

  - title: Slaapkamer Saar
    panel: true
    cards:
      - type: custom:layout-card
        layout: horizontal
        column_num: 2
        cards:
          - type: glance
            entities:
              - entity: sensor.sensor_slaapkamer_saar__lichtsterkte
                name: Lichtsterkte
                icon: 'mdi:white-balance-sunny'
              - entity: sensor.sensor_slaapkamer_saar__luchtvochtigheid
                name: Luchtvochtigheid
                icon: 'mdi:water-percent'
              - entity: sensor.sensor_slaapkamer_saar__temperatuur
                name: Temperatuur
          - type: glance
            entities:
              - entity: sensor.sensor_slaapkamer_saar__pir
                name: Beweging?
              - entity: light.slaapkamer_saar__led
                name: Led
                icon: 'mdi:lamp'
          - <<: *compact-header

  - title: Zolder
    panel: true
    cards:
      - type: custom:layout-card
        layout: horizontal
        column_num: 2
        cards:
          - type: glance
            entities:
              - entity: sensor.sensor_zolder__lichtsterkte
                name: Lichtsterkte
                icon: 'mdi:white-balance-sunny'
              - entity: sensor.sensor_zolder__luchtvochtigheid
                name: Luchtvochtigheid
                icon: 'mdi:water-percent'
              - entity: sensor.sensor_zolder__temperatuur
                name: Temperatuur
          - type: glance
            entities:
              - entity: sensor.sensor_zolder__pir
                name: Beweging?
              - entity: light.zolder__led
                name: Led
                icon: 'mdi:lamp'
          - <<: *compact-header

  - title: Overig
    cards:
      - type: custom:tracker-card
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

      - type: custom:mini-media-player
        entity: media_player.woonkamer_2
        hide_controls: true
        show_tts: google
        power_color: true
        hide_power: true

      - type: entity-button
        entity: input_boolean.play_saskia_pick_up_sound
        tap_action: toggle

      - type: entities
        entities:
          - entity: group.all_automations
            name: Automations
          - entity: group.all_devices
            name: All devices
          - entity: group.all_lights
            name: All lights
          - entity: sensor.sensor_slaapkamer_saar__pir
            name: Beweging?
          - entity: group.all_switches
            name: All lights

      - <<: *compact-header
