resources:
  - url: /local/lovelace/card-tools.js?v=f5bb8e
    type: js
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.1
    type: module
  - url: /local/lovelace/layout-card.js?v=2b29c0
    type: module
  - url: /local/lovelace/useful-markdown-card.js?v=9377d8
    type: module
  - url: /local/lovelace/slider-entity-row.js?v=be80ff
    type: js
  - url: /local/lovelace/tracker-card.js?v=0.3.2
    type: js

# Images for Afvalwijzer
x-afval-images: &afval-images
- state_image:
    "gft": /local/afvalwijzer/gft_large.png
    "papier": /local/afvalwijzer/papier_large.png
    "restafval": /local/afvalwijzer/rest_large.png
    "plastic": /local/afvalwijzer/plastic_large.png
    "Geen": /local/afvalwijzer/kliko.png

views:
  - title: Home
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: glance
            entities:
              - device_tracker.iphonesjors
              - device_tracker.iphone_van_saskia

          # - type: entities
          #   entities:
          #     - entity: input_select.hue_switch
          #     - entity: sensor.hue_switch_updated
          #     - entity: sensor.hue_switch

          # - type: entities
          #   entities:
          #     - type: custom:slider-entity-row
          #       entity: light.all_hue_lights
          #       name: Helderheid
          #       icon: mdi:brightness-6
          #     - entity: input_select.hue_scenes
          #     - entity: script.set_hue_scene
          #       name: Activeer scene
          #       secondary_info: last-changed
          #       icon: mdi:play

          - type: entities
            entities:
              - entity: switch.sonoff04_basic_relay
                secondary_info: last-changed
              - entity: switch.neo_coolcam_power_plug_12a_switch_3
                secondary_info: last-changed

          - break

          - type: horizontal-stack
            cards:
              - type: glance
                title: Temperatuur
                entities:
                  - entity: sensor.multisensor02_temperature
                    name: Zolder
                  - entity: sensor.multisensor01_temperature
                    name: Saar
              - type: glance
                title: Beweging
                entities:
                  - entity: binary_sensor.multisensor02_motion
                    name: Zolder
                  - entity: binary_sensor.multisensor01_motion
                    name: Saar

          - type: vertical-stack
            cards:
              - type: glance
                entities:
                  - entity: sensor.wasmachine_verbruik
                  - entity: sensor.droger_verbruik
                  - entity: sensor.vaatwasser_verbruik
                  - entity: sensor.tv_verbruik

          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: sensor.trash_today
                <<: *afval-images
              - type: picture-entity
                entity: sensor.trash_tomorrow
                <<: *afval-images

          - type: custom:useful-markdown-card
            content: >
              Vandaag is het [[ sensor.date_formatted.state ]] nog [[  sensor.trash_next.state ]] dag(en) tot de volgende pickup

          - type: glance
            entities:
              - entity: sensor.trash_gft_formatted
              - entity: sensor.trash_papier_formatted
              - entity: sensor.trash_plastic_formatted
              - entity: sensor.trash_restafval_formatted

          - break

          - type: weather-forecast
            entity: weather.dark_sky

          - type: picture-entity
            entity: camera.weer
            aspect_ratio: 16:9

  - title: Beneden
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - type: custom:slider-entity-row
                entity: light.woonkamer
              - type: custom:slider-entity-row
                entity: light.eetkamer
              - type: custom:slider-entity-row
                entity: light.keuken

          - break

          - type: entities
            title: Woonkamer
            show_header_toggle: false
            entities:
              - type: custom:slider-entity-row
                entity: light.hue_color_lamp_1
                icon: mdi:floor-lamp
                name: Lamp
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_2
                icon: mdi:spotlight-beam
                name: Spot 1
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_4
                icon: mdi:spotlight-beam
                name: Spot 2
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_3
                icon: mdi:spotlight-beam
                name: Spot 3
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_1
                icon: mdi:spotlight-beam
                name: Spot 4

          - break

          - type: entities
            title: Eetkamer
            show_header_toggle: false
            entities:
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_lamp_1
                name: Lamp 1
              - type: custom:slider-entity-row
                entity: light.hue_color_lamp_1_2
                name: Lamp 2
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_lamp_2
                name: Lamp 3
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_2_3
                icon: mdi:spotlight-beam
                name: Spot 1
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_3_3
                icon: mdi:spotlight-beam
                name: Spot 2

          - break

          - type: entities
            title: Keuken
            show_header_toggle: false
            entities:
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_1_2
                icon: mdi:spotlight-beam
                name: Spot 1
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_2_2
                icon: mdi:spotlight-beam
                name: Spot 2
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_3_2
                icon: mdi:spotlight-beam
                name: Spot 3
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_4_2
                icon: mdi:spotlight-beam
                name: Spot 4
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_1_3
                icon: mdi:spotlight-beam
                name: Spot 5
              - type: custom:slider-entity-row
                entity: light.hue_ambiance_spot_4_3
                icon: mdi:spotlight-beam
                name: Spot 6

  - title: Boven
    cards:
      - type: entities
        title: "Slaapkamer Saar"
        show_header_toggle: false
        entities:
          - entity: sensor.multisensor01_brightness
            secondary_info: last-changed
          - entity: sensor.multisensor01_humidity
            secondary_info: last-changed
          - entity: sensor.multisensor01_temperature
            secondary_info: last-changed
          - entity: binary_sensor.multisensor01_motion
            secondary_info: last-changed
          - entity: light.multisensor01_light
            secondary_info: last-changed

      - type: entities
        title: "Zolder"
        show_header_toggle: false
        entities:
          - entity: sensor.multisensor02_brightness
            secondary_info: last-changed
          - entity: sensor.multisensor02_humidity
            secondary_info: last-changed
          - entity: sensor.multisensor02_temperature
            secondary_info: last-changed
          - entity: binary_sensor.multisensor02_motion
            secondary_info: last-changed
          - entity: light.multisensor02_light
            secondary_info: last-changed

  - title: Overig
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: custom:tracker-card
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker

          - type: entities
            entities:
              - entity: group.all_automations
                name: Automations
              - entity: group.all_devices
                name: All devices
              - entity: group.all_lights
                name: All lights
              # - entity: sensor.sensor_slaapkamer_saar__pir
              #   name: Beweging?
              - entity: group.all_switches
                name: All lights

          - break

          - type: custom:mini-media-player
            entity: media_player.google_home_mini
            tts:
              platform: google

          - type: entities
            entities:
              - entity: input_boolean.play_saskia_pick_up_sound
                secondary_info: last-changed