- type: css
  url: 'https://fonts.googleapis.com/css?family=Open+Sans&display=swap'

- type: module
  url: /community_plugin/mini-media-player/mini-media-player-bundle.js

- type: module
  url: /community_plugin/button-card/button-card.js

- type: module
  url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js

- type: module
  url: /community_plugin/decluttering-card/decluttering-card.js

- type: module
  url: /community_plugin/lovelace-layout-card/layout-card.js

- type: module
  url: /community_plugin/lovelace-card-tools/card-tools.js

- type: module
  url: /community_plugin/lovelace-card-mod/card-mod.js

- type: module
  url: /community_plugin/custom-header/custom-header.js

- type: module
  url: /community_plugin/power-usage-card/power-usage-card.js

- type: js
  url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js

- type: js
  url: /community_plugin/upcoming-media-card/upcoming-media-card.js

- type: js
  url: /community_plugin/gauge-card/gauge-card.js
