- alias: Reset trash notification
  trigger:
    platform: state
    entity_id: input_boolean.trash_moved
    to: 'on'
    for:
      hours: 12
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.trash_moved
    - service: input_boolean.turn_on
      entity_id: input_boolean.trash_reminder

- alias: Mark trash as moved from notification
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: MARK_TRASH_MOVED
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.trash_moved

- alias: Trash has not been moved
  trigger:
    platform: time_pattern
    minutes: '/30'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.trash_moved
        state: 'off'
      - condition: state
        entity_id: input_boolean.trash_reminder
        state: 'on'
      - condition: time
        after: '18:00:00'
        before: '23:00:00'
      - condition: template
        value_template: "{{ states('sensor.trash_tomorrow') != 'Geen' }}"
  action:
    - service: notify.ios_iphonesjors
      data:
        title: "Afval"
        message: 'Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. Afvaltype(n): {{ states.sensor.trash_tomorrow.state }} wordt opgehaald op: {{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%d-%m-%Y", True) }}!'
        data:
          push:
            badge: 0
            category: 'afval'