alias: 'Tuinverlichting uit om 00:00'
trigger:
  - platform: time
    at: '00:00:00'
condition:
  - condition: state
    entity_id: 'input_boolean.auto_backyard_lights_off'
    state: 'on'
action:
  - service: switch.turn_off
    entity_id: group.backyard