- alias: Vaatwasser - bezig
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      above: '3'
      entity_id: sensor.vaatwasser_verbruik
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dishwasher_busy

- alias: Vaatwasser - klaar
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      below: '3'
      entity_id: sensor.vaatwasser_verbruik
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dishwasher_busy

- alias: Vaatwasser - notificatie Google home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dishwasher_busy
      from: 'on'
      to: 'off'
      # for:
      #   minutes: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.occupancy_simulator
        state: 'off'
      - condition: template
        value_template: "{{ is_state('device_tracker.iphone','home') or is_state('device_tracker.iphone_van_saskia','home') }}"
      - condition: time
        after: '08:00:00'
        before: '22:00:00'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.broadcast
        volume_level: '0.50'
    - service: tts.google_say
      entity_id: media_player.broadcast
      data:
        message: 'De vaatwasser is klaar!'

- alias: Vaatwasser - notificatie Sjors
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dishwasher_busy
      from: 'on'
      to: 'off'
      # for:
      #   minutes: 30
  condition:
    - condition: template
      value_template: "{{ is_state('device_tracker.iphone','home') }}"
  action:
    - service: notify.ios_iphone
      data:
        title: 'Vaatwasser: '
        message: Ik ben klaar!

- alias: Vaatwasser - notificatie Saskia
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dishwasher_busy
      from: 'on'
      to: 'off'
      # for:
      #   minutes: 30
  condition:
    - condition: template
      value_template: "{{ is_state('device_tracker.iphone_van_saskia','home') }}"
  action:
    - service: notify.ios_iphone_van_saskia
      data:
        title: 'Vaatwasser: '
        message: Ik ben klaar!