#  Vaatwasser - BUSY
- alias: Vaatwasser - bezig
  trigger:
    - platform: numeric_state
      above: '2'
      entity_id: sensor.vaatwasser_verbruik

  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.dishwasher_busy

# Vaatwasser - DONE
- alias: Vaatwasser - klaar
  trigger:
    - platform: numeric_state
      below: '1.5'
      entity_id: sensor.vaatwasser_verbruik

  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.dishwasher_busy

# Vaatwasser - NOTIFICATION
- alias: Vaatwasser - notificatie
  trigger:
    - platform: state
      entity_id: input_boolean.dishwasher_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 30

  action:
    - service: notify.ios_iphonesjors
      data:
        title: 'Vaatwasser: '
        message: Ik ben klaar!
    - service: notify.ios_iphone_van_saskia
      data:
        title: 'Vaatwasser: '
        message: Ik ben klaar!
    - service: media_player.volume_set
      data:
        entity_id:
          - media_player.woonkamer_2
        volume_level: '0.50'
    - service: tts.google_say
      entity_id:
        - media_player.woonkamer_2
      data_template:
        message: 'De vaatwasser is klaar!'