- alias: Droger - bezig
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      above: '2'
      entity_id: sensor.droger_verbruik
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dryer_busy

- alias: Droger - klaar
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      below: '1.5'
      entity_id: sensor.droger_verbruik
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dryer_busy

- alias: Droger - notificatie Google home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dryer_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.occupancy_simulator
      state: 'off'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home
        volume_level: '0.50'
    - service: tts.google_say
      entity_id: media_player.google_home
      data:
        message: 'De droger is klaar!'

- alias: Droger - notificatie Sjors
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dryer_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: template
      value_template: "{{ is_state('device_tracker.iphonesjors','home') }}"
  action:
    - service: notify.ios_iphonesjors
      data:
        title: 'Droger: '
        message: Ik ben klaar!

- alias: Droger - notificatie Saskia
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dryer_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: template
      value_template: "{{ is_state('device_tracker.iphone_van_saskia','home') }}"
  action:
    - service: notify.ios_iphone_van_saskia
      data:
        title: 'Droger: '
        message: Ik ben klaar!