# Droger - BUSY
- alias: Droger - bezig
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      above: '2'
      entity_id: sensor.droger_verbruik
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dryer_busy

# Droger - DONE
- alias: Droger - klaar
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      below: '1.5'
      entity_id: sensor.droger_verbruik
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dryer_busy

# Droger - NOTIFICATION
- alias: Droger - notificatie
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dryer_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  action:
    - service: notify.ios_iphonesjors
      data:
        title: 'Droger: '
        message: Ik ben klaar!
    - service: notify.ios_iphone_van_saskia
      data:
        title: 'Droger: '
        message: Ik ben klaar!
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_mini
        volume_level: '0.50'
    - service: tts.google_say
      entity_id: media_player.google_home_mini
      data:
        message: 'De droger is klaar!'