alias: Dryer done notification
trigger:
  - platform: state
    entity_id: input_boolean.dryer_busy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
action:
  - service: notify.ios_iphonesaskia
    data:
      title: "Droger: "
      message: "Ik ben klaar!"
  - service: notify.ios_iphonesjors
    data:
      title: "Droger: "
      message: "Ik ben klaar!"