# Good Morning Routines - ON
- alias: 'Good Morning Weekdays Routine - ON'
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:40:00'
  condition:
  - condition: sun
    before: sunrise
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 255
        transition: 300
    - service: light.turn_on
      data:
        entity_id: light.keuken
        brightness: 255
        transition: 300

- alias: 'Good Morning Weekend Routine - ON'
  initial_state: 'on'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    - condition: sun
      before: sunrise
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 255
        transition: 300
    - service: light.turn_on
      entity_id: light.keuken
      data:
        brightness: 255
        transition: 300

# Good Morning Routines - OFF
- alias: 'Good Morning Weekdays Routine - OFF'
  initial_state: 'on'
  trigger:
    platform: time
    at: '08:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_off
      data:
        entity_id: light.woonkamer
        transition: 300
    - service: light.turn_off
      data:
        entity_id: light.keuken
        transition: 300
    - service: light.turn_off
      data:
        entity_id: light.eetkamer
        transition: 300

- alias: 'Good Morning Weekend Routine - OFF'
  initial_state: 'on'
  trigger:
    platform: time
    at: '10:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: light.turn_off
      data:
        entity_id: light.woonkamer
        transition: 300
    - service: light.turn_off
      data:
        entity_id: light.keuken
        transition: 300
    - service: light.turn_off
      data:
        entity_id: light.eetkamer
        transition: 300