- alias: 'Good Night Routine - ON'
  initial_state: 'on'
  trigger:
    platform: sun
    event: 'sunset'
    offset: '-00:15:00'
  condition:
    - condition: state
      entity_id: input_boolean.occupancy_simulator
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 255
        transition: 300
    - service: light.turn_on
      data:
        entity_id: light.keuken
        brightness: 255
        transition: 300

- alias: 'Good Night Routine - OFF'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.occupancy_simulator
        state: 'off'
      - condition: state
        entity_id: input_boolean.babysitter
        state: 'off'
      - condition: time
        after: '23:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - sun
  action:
    - service: light.turn_off
      data:
        entity_id: light.woonkamer
        transition: 300
    - service: light.turn_off
      data:
        entity_id: light.keuken
        transition: 300
    - service: light.turn_off
      data:
        entity_id: light.eetkamer
        transition: 300

- alias: 'Good Night Routine - OFF weekends'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '01:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.occupancy_simulator
        state: 'off'
      - condition: state
        entity_id: input_boolean.babysitter
        state: 'off'
      - condition: time
        after: '01:00:00'
        weekday:
          - fri
          - sat
  action:
    - service: light.turn_off
      data:
        entity_id: light.woonkamer
        transition: 300
    - service: light.turn_off
      data:
        entity_id: light.keuken
        transition: 300
    - service: light.turn_off
      data:
        entity_id: light.eetkamer
        transition: 300