# https://www.lolgast.nl/hue-tap-home-assistant/
- alias: Hue Tap buttonevent Sync
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.hue_switch_updated
  condition:
    - condition: template
      value_template: >
         {%- set tmstmp = states.sensor.hue_switch_updated.state.split('T')[1] %}
         {% set hours = tmstmp.split(':')[0] %}
         {% set minutes = tmstmp.split(':')[1] %}
         {% set time = hours ~ ':' ~ minutes %}
         {% if (states.sensor.time_utc.state | string) == (time | string)  %} True
         {% else %} False
         {% endif %}
  action:
    - delay:
        milliseconds: 150
    - service: input_select.select_option
      entity_id: input_select.hue_switch
      data_template:
        option: >
          {% if is_state('sensor.hue_switch', '20') %} 20
          {% elif is_state('sensor.hue_switch', '21') %} 21
          {% elif is_state('sensor.hue_switch', '22') %} 22
          {% elif is_state('sensor.hue_switch', '23') %} 23
          {% endif %}

- alias: Hue Tap Button Top Left
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.hue_switch
      to: '20'
      from: '-'
  action:
    - service: light.turn_on
      data:
        entity_id: light.woonkamer
    - service: light.turn_on
      data:
        entity_id: light.keuken
    - service: light.turn_on
      data:
        entity_id: light.eetkamer
    - service: input_select.select_option
      data:
        entity_id: input_select.hue_tap
        option: '-'