- alias: Turn on Occupancy Simulator
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunset
      offset: '00:15:00'
  condition:
    - condition: state
      entity_id: input_boolean.occupancy
      state: 'off'
  action:
    - delay: '00:{{ range(10,40) | random | int }}:00'

    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.keuken
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_on
      data:
        entity_id: light.eetkamer
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.keuken

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 200

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: homeassistant.turn_off
      data:
        entity_id: light.eetkamer

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: homeassistant.turn_on
      data:
        entity_id: light.keuken
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: homeassistant.turn_off
      data:
        entity_id: light.keuken

    - delay: '00:{{ range(10,40) | random | int }}:00'

    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_on
      data:
        entity_id: light.eetkamer
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.keuken

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 200

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: homeassistant.turn_off
      data:
        entity_id: light.eetkamer

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: homeassistant.turn_on
      data:
        entity_id: light.keuken
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: homeassistant.turn_off
      data:
        entity_id: light.keuken

- alias: Turn off Occupancy Simulator
  initial_state: 'on'
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.occupancy
      state: 'off'
  action:
    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.woonkamer

    - service: light.turn_off
      data:
        entity_id: light.eetkamer

    - service: light.turn_off
      data:
        entity_id: light.keuken