- alias: Play sound - Saskia pick up
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.play_saskia_pick_up_sound
      from: 'off'
      to: 'on'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.broadcast
        volume_level: '1.0'
    - service: tts.google_say
      entity_id: media_player.broadcast
      data:
        message: 'Saskia neem je telefoon eens op'
        language: 'nl'
    - service: media_player.volume_set
      data:
        entity_id: media_player.broadcast
        volume_level: '0.5'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.play_saskia_pick_up_sound