- alias: 'TV - ON'
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:15:00'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.tv_switch

- alias: 'TV - OFF'
  initial_state: 'on'
  trigger:
    platform: time
    at: '01:00:00'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.tv_switch