- alias: 'TV - ON'
  initial_state: 'on'
  trigger:
    platform: time
    at: '06:25:00'
  condition:
    - condition: state
      entity_id: input_boolean.occupancy
      state: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.tv_switch

- alias: 'TV - OFF'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '01:00:00'
    - platform: state
      entity_id: input_boolean.occupancy
      from: 'on'
      from: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.tv_switch