
- alias: Location - Update
  trigger:
    - platform: time_pattern
      minutes: /10

  action:
    - service: notify.ios_iphone
      data:
        message: request_location_update
    - service: notify.ios_iphone_van_saskia
      data:
        message: request_location_update