- alias: Update notifications
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.ios_iphone
      data:
        title: 'Update beschikbaar: '
        message: Home Assistant {{ states('updater.updater') }} is beschikbaar. Er zijn {{ states('sensor.potential_breaking_changes') }} potentiële breaking changes. Wil je updaten?

- alias: Update notifications HACS
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.hacs
      above: 0
  action:
    - service: notify.ios_iphone
      data:
        title: 'Update beschikbaar: '
        message: Er zijn {{ states('sensor.hacs') }} updates voor componenten. Wil je updaten?