alias: Washingmachine busy
trigger:
  - platform: numeric_state
    entity_id: !secret washingmachine_power_usage
    above: 10
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.washingmachine_busy