alias: Washmingmachine done notification
trigger:
  - platform: state
    entity_id: input_boolean.washingmachine_busy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: !secret livingroom_light
    state: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.woonkamer_flash_blauw
  - delay:
      seconds: 15
  - service: light.hue_activate_scene
    data:
      group_name: "Woonkamer"
      scene_name: "Ontspannen"

# Todo
# - return light to previous state (on/off/scene)