- alias: Wasmachine - bezig
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      above: '2'
      entity_id: sensor.wasmachine_verbruik
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.washingmachine_busy

- alias: Wasmachine - klaar
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      below: '5'
      entity_id: sensor.wasmachine_verbruik
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.washingmachine_busy

- alias: Wasmachine - notificatie google home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.washingmachine_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: template
      value_template: "{{ is_state('device_tracker.iphonesjors','home') or is_state('device_tracker.iphone_van_saskia','home') }}"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home
        volume_level: '0.50'
    - service: tts.google_say
      entity_id: media_player.google_home
      data:
        message: 'De wasmachine is klaar!'

- alias: Wasmachine - notificatie Sjors
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.washingmachine_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: template
      value_template: "{{ is_state('device_tracker.iphonesjors','home') }}"
  action:
    - service: notify.ios_iphonesjors
      data:
        title: 'Wasmachine: '
        message: Ik ben klaar!

- alias: Wasmachine - notificatie Saskia
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.washingmachine_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: template
      value_template: "{{ is_state('device_tracker.iphone_van_saskia','home') }}"
  action:
    - service: notify.ios_iphone_van_saskia
      data:
        title: 'Wasmachine: '
        message: Ik ben klaar!
