alias: Washingmachine busy
trigger:
  - platform: numeric_state
    entity_id: sensor.schuur__wasmachine_power
    below: 9
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.washingmachine_busy