alias: Washmingmachine done notification
trigger:
  - platform: state
    entity_id: input_boolean.washingmachine_busy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
action:
  - service: notify.ios_iphonesaskia
    data:
      title: "Wasmachine: "
      message: "Ik ben klaar!"
  - service: notify.ios_iphonesjors
    data:
      title: "Wasmachine: "
      message: "Ik ben klaar!"