# Washing Machine - BUSY
- alias: Wasmachine - bezig
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      above: '2'
      entity_id: sensor.wasmachine_verbruik
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.washingmachine_busy

# Washing Machine - DONE
- alias: Wasmachine - klaar
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      below: '5'
      entity_id: sensor.wasmachine_verbruik
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.washingmachine_busy

# Washing Machine - NOTIFICATION
- alias: Wasmachine - notificatie
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.washingmachine_busy
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  action:
    - service: notify.ios_iphonesjors
      data:
        title: 'Wasmachine: '
        message: Ik ben klaar!
    - service: notify.ios_iphone_van_saskia
      data:
        title: 'Wasmachine: '
        message: Ik ben klaar!
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_mini
        volume_level: '0.50'
    - service: tts.google_say
      entity_id: media_player.google_home_mini
      data:
        message: 'De wasmachine is klaar!'

