- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Wekker'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_slider.alarm_hour") | int, states("input_slider.alarm_minutes") | int) }}'
