- platform: mqtt
  state_topic: "/energy/p1"
  name: "Power consumption - low tariff"
  unit_of_measurement: "kWh"
  force_update: true
  value_template: '{{ value_json.powerConsumptionLowTariff | int }}'

- platform: mqtt
  state_topic: "/energy/p1"
  name: "Power consumption - high tariff"
  unit_of_measurement: "kWh"
  force_update: true
  value_template: '{{ value_json.powerConsumptionHighTariff | int }}'

- platform: mqtt
  state_topic: "/energy/p1"
  name: "Power production - low tariff"
  unit_of_measurement: "kWh"
  force_update: true
  value_template: '{{ value_json.powerProductionLowTariff | int }}'

- platform: mqtt
  state_topic: "/energy/p1"
  name: "Power production - high tariff"
  unit_of_measurement: "kWh"
  force_update: true
  value_template: '{{ value_json.powerProductionHighTariff | int }}'

- platform: mqtt
  state_topic: "/energy/p1"
  name: "Current power consumption"
  unit_of_measurement: "kW"
  force_update: true
  value_template: '{{ value_json.CurrentPowerConsumption | int }}'

- platform: mqtt
  state_topic: "/energy/p1"
  name: "Current power production"
  unit_of_measurement: "kWh"
  force_update: true
  value_template: '{{ value_json.CurrentPowerProduction | int }}'

- platform: mqtt
  state_topic: "/energy/p1"
  name: "Gas consumption"
  unit_of_measurement: "kWh"
  force_update: true
  value_template: '{{ value_json.GasConsumption | int }}'