# ---------------------------------------------------------- #
# SENSOR KANTOOR - WHITE
# ---------------------------------------------------------- #
- platform: mqtt  
  state_topic: "homeassistant/multisensor01"  
  name: "Sensor Kantoor - Luchtvochtigheid"
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  

- platform: mqtt  
  state_topic: "homeassistant/multisensor01"  
  name: "Sensor Kantoor - Lichtsterkte"
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  

- platform: mqtt  
  state_topic: "homeassistant/multisensor01"  
  name: "Sensor Kantoor - PIR"  
  value_template: '{{ value_json.motion }}'  

- platform: mqtt  
  state_topic: "homeassistant/multisensor01"  
  name: "Sensor Kantoor - Temperatuur"
  unit_of_measurement: "째C"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "homeassistant/multisensor01"
  name: "Sensor Kantoor - Temperatuur heat index"
  unit_of_measurement: "째C"
  value_template: '{{ value_json.heatIndex | round(1) }}'

# ---------------------------------------------------------- #
# SENSOR SLAAPKAMER SAAR - GREEN
# ---------------------------------------------------------- #
- platform: mqtt  
  state_topic: "homeassistant/multisensor02"  
  name: "Sensor Slaapkamer Saar - Luchtvochtigheid"
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  

- platform: mqtt  
  state_topic: "homeassistant/multisensor02"  
  name: "Sensor Slaapkamer Saar - Lichtsterkte"
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  

- platform: mqtt  
  state_topic: "homeassistant/multisensor02"  
  name: "Sensor Slaapkamer Saar - PIR"  
  value_template: '{{ value_json.motion }}'  

- platform: mqtt  
  state_topic: "homeassistant/multisensor02"  
  name: "Sensor Slaapkamer Saar - Temperatuur"
  unit_of_measurement: "째C"  
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "homeassistant/multisensor02"
  name: "Sensor Slaapkamer Saar - Temperatuur heat index"
  unit_of_measurement: "째C"
  value_template: '{{ value_json.heatIndex | round(1) }}'