# SENSOR Woonkamer - WHITE
- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Sensor Woonkamer - Luchtvochtigheid"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Sensor Woonkamer - Lichtsterkte"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Sensor Woonkamer - Bewegingsmelder"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Sensor Woonkamer - Temperatuur"
  unit_of_measurement: "°F" # Shown in Celcius in the frontend
  value_template: '{{ value_json.temperature | round(1) }}'

# SENSOR Slaapkamer Saar - GREEN
- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "Sensor Slaapkamer Saar - Luchtvochtigheid"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "Sensor Slaapkamer Saar - Lichtsterkte"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "Sensor Slaapkamer Saar - Bewegingsmelder"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "Sensor Slaapkamer Saar - Temperatuur"
  unit_of_measurement: "°F" # Shown in Celcius in the frontend
  value_template: '{{ value_json.temperature | round(1) }}'