# SENSOR 01 - WHITE
- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Sensor 01 - Luchtvochtigheid"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Sensor 01 - Lichtsterkte"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Sensor 01 - Bewegingsmelder"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Sensor 01 - Temperatuur"
  unit_of_measurement: "°F" # Shown in Celcius in the frontend
  value_template: '{{ value_json.temperature | round(1) }}'

# SENSOR 02 - GREEN
- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "Sensor 02 - Luchtvochtigheid"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "Sensor 02 - Lichtsterkte"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "Sensor 02 - Bewegingsmelder"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "bruh/sensornode2"
  name: "Sensor 02 - Temperatuur"
  unit_of_measurement: "°F" # Shown in Celcius in the frontend
  value_template: '{{ value_json.temperature | round(1) }}'