- platform: plex_recently_added
  token: !secret plex_token
  host: !secret plex_ip
  port: !secret plex_port
  max: 3
  section_types:
    - movie

- platform: plex_recently_added
  token: !secret plex_token
  host: !secret plex_ip
  port: !secret plex_port
  max: 3
  section_types:
    - show