- platform: template
  sensors:
    date_formatted:
      entity_id: sensor.date
      value_template: '{{ as_timestamp(strptime(states.sensor.date.state, "%Y-%m-%d")) | timestamp_custom("%a %d %b") }}'