  - platform: template
    sensors:
      trash_gft_formatted:
        entity_id: sensor.trash_gft
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_gft.state, "%Y-%m-%d")) | timestamp_custom("%a %d %b") }}'
      trash_papier_formatted:
        entity_id: sensor.trash_papier
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_papier.state, "%Y-%m-%d")) | timestamp_custom("%a %d %b") }}'
      trash_plastic_verpakkingsafval_formatted:
        entity_id: sensor.trash_plastic_verpakkingsafval
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_plastic_verpakkingsafval.state, "%Y-%m-%d")) | timestamp_custom("%a %d %b") }}'
      trash_restafval_formatted:
        entity_id: sensor.trash_restafval
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_restafval.state, "%Y-%m-%d")) | timestamp_custom("%a %d %b") }}'
      date_formatted:
        entity_id: sensor.date
        value_template: '{{ as_timestamp(strptime(states.sensor.date.state, "%Y-%m-%d")) | timestamp_custom("%a %d %b") }}'