# Weer
sun.sun:
  hidden: true

# Woonkamer
# Philips Hue
!secret livingroom_light:
  friendly_name: "Lamp Woonkamer"
  icon: "mdi:lightbulb-outline"
light.hue_color_lamp_2:
  hidden: true

# Televisie
sensor.woonkamer__televisie_alarm_level_9_1:
  hidden: true
sensor.woonkamer__televisie_alarm_type_9_0:
  hidden: true
sensor.woonkamer__televisie_current_9_20:
  hidden: true
sensor.woonkamer__televisie_energy_9_0:
  hidden: true
sensor.woonkamer__televisie_exporting_9_32:
  hidden: true
sensor.woonkamer__televisie_interval_9_10:
  hidden: true
sensor.woonkamer__televisie_interval_9_18:
  hidden: true
sensor.woonkamer__televisie_interval_9_2:
  hidden: true
sensor.woonkamer__televisie_interval_9_22:
  hidden: true
!secret television_power_usage:
  friendly_name: "Televisie verbruik (w)"
  icon: "mdi:power-plug"
sensor.woonkamer__televisie_power_management_9_11:
  hidden: true
sensor.woonkamer__televisie_previous_reading_9_1:
  hidden: true
sensor.woonkamer__televisie_previous_reading_9_17:
  hidden: true
sensor.woonkamer__televisie_previous_reading_9_21:
  hidden: true
sensor.woonkamer__televisie_previous_reading_9_9:
  hidden: true
sensor.woonkamer__televisie_sourcenodeid_9_2:
  hidden: true
sensor.woonkamer__televisie_voltage_9_16:
  hidden: true
!secret television_toggle:
  friendly_name: "Televisie"
  icon: "mdi:television-guide"
zwave.woonkamer__televisie_9:
  hidden: true

# Woonkamer PIR
binary_sensor.woonkamer__bewegingsmelder_sensor: # state: on/off
  name: "Beweging"
  icon: "mdi:run"
sensor.woonkamer__bewegingsmelder_alarm_level:
  hidden: true
sensor.woonkamer__bewegingsmelder_alarm_type:
  hidden: true
sensor.woonkamer__bewegingsmelder_burglar:
  hidden: true
sensor.woonkamer__bewegingsmelder_luminance_10_3:
  name: "Light"
  icon: "mdi:white-balance-sunny"
sensor.woonkamer__bewegingsmelder_sourcenodeid_10_2:
  hidden: true
zwave.woonkamer__bewegingsmelder_10:
  hidden: true

# Achtertuin
sensor.achtertuin__led_lampjes_energy:
  hidden: true
sensor.achtertuin__led_lampjes_power:
  hidden: true
sensor.achtertuin__led_lampjes_previous_reading:
  hidden: true
sensor.achtertuin__led_lampjes_previous_reading_2:
  hidden: true
!secret backyard_light_toggle:
  friendly_name: "Verlichting"
  icon: "mdi:led-outline"
zwave.achtertuin__led_lampjes_3:
  hidden: true

# Apparaten
# Vaatwasser
sensor.woonkamer__vaatwasser_energy_2_0:
  hidden: true
!secret dishwasher_power_usage:
  friendly_name: "Vaatwasser verbruik"
  icon: "mdi:power-plug"
sensor.woonkamer__vaatwasser_previous_reading_2_1:
  hidden: true
sensor.woonkamer__vaatwasser_previous_reading_2_9:
  hidden: true
!secret dishwasher_power_toggle:
  friendly_name: "Vaatwasser"
  icon: "mdi:washing-machine"
zwave.woonkamer__vaatwasser_2:
  hidden: true

# Wasmachine
sensor.schuur__wasmachine_alarm_level:
  hidden: true
sensor.schuur__wasmachine_alarm_type:
  hidden: true
sensor.schuur__wasmachine_current:
  hidden: true
sensor.schuur__wasmachine_energy:
  hidden: true
sensor.schuur__wasmachine_exporting:
  hidden: true
sensor.schuur__wasmachine_interval:
  hidden: true
sensor.schuur__wasmachine_interval_2:
  hidden: true
sensor.schuur__wasmachine_interval_3:
  hidden: true
sensor.schuur__wasmachine_interval_4:
  hidden: true
!secret washingmachine_power_usage:
  friendly_name: "Wasmachine verbruik"
  icon: "mdi:power-plug"
sensor.schuur__wasmachine_power_management:
  hidden: true
sensor.schuur__wasmachine_previous_reading:
  hidden: true
sensor.schuur__wasmachine_previous_reading_2:
  hidden: true
sensor.schuur__wasmachine_previous_reading_3:
  hidden: true
sensor.schuur__wasmachine_previous_reading_4:
  hidden: true
sensor.schuur__wasmachine_sourcenodeid:
  hidden: true
sensor.schuur__wasmachine_voltage:
  hidden: true
!secret washingmachine_power_toggle:
  friendly_name: "Wasmachine"
  icon: "mdi:washing-machine"
zwave.schuur__wasmachine:
  hidden: true

# Droger
sensor.schuur__droger_alarm_level:
  hidden: true
sensor.schuur__droger_alarm_type:
  hidden: true
sensor.schuur__droger_current:
  hidden: true
sensor.schuur__droger_energy:
  hidden: true
sensor.schuur__droger_exporting:
  hidden: true
sensor.schuur__droger_interval:
  hidden: true
sensor.schuur__droger_interval_2:
  hidden: true
sensor.schuur__droger_interval_3:
  hidden: true
sensor.schuur__droger_interval_4:
  hidden: true
!secret dryer_power_usage:
  friendly_name: "Droger verbruik"
  icon: "mdi:power-plug"
sensor.schuur__droger_power_management:
  hidden: true
sensor.schuur__droger_previous_reading:
  hidden: true
sensor.schuur__droger_previous_reading_2:
  hidden: true
sensor.schuur__droger_previous_reading_3:
  hidden: true
sensor.schuur__droger_previous_reading_4:
  hidden: true
sensor.schuur__droger_sourcenodeid:
  hidden: true
sensor.schuur__droger_voltage:
  hidden: true
!secret dryer_power_toggle:
  friendly_name: "Droger"
  icon: "mdi:washing-machine"
zwave.schuur__droger:
  hidden: true

# Woonkamer MultiSensor
sensor.sensor_woonkamer__temperatuur:
  friendly_name: Temperatuur
sensor.sensor_woonkamer__luchtvochtigheid:
  friendly_name: Luchtvochtigheid
sensor.sensor_woonkamer__lichtsterkte:
  friendly_name: Lichtsterkte
sensor.sensor_woonkamer__bewegingsmelder:
  friendly_name: Bewegingsmelder
light.woonkamer__led:
  friendly_name: Lampje

sensor.sensor_slaapkamer_saar__temperatuur:
  friendly_name: Temperatuur
sensor.sensor_slaapkamer_saar__luchtvochtigheid:
  friendly_name: Luchtvochtigheid
sensor.sensor_slaapkamer_saar__lichtsterkte:
  friendly_name: Lichtsterkte
sensor.sensor_slaapkamer_saar__bewegingsmelder:
  friendly_name: Bewegingsmelder
light.slaapkamer_saar__led:
  friendly_name: Lampje

zwave.aeotec_zw090_zstick_gen5:
  hidden: true

binary_sensor.floorplan:
  custom_ui_state_card: floorplan
  config: !include floorplan.yaml