# Weer
sun.sun:
  hidden: true

# Woonkamer
# Philips Hue
light.hue_color_lamp_1:
  friendly_name: "Lamp Woonkamer"
  icon: "mdi:lightbulb-outline"
light.hue_color_lamp_2:
  hidden: true

# Televisie
sensor.woonkamer__televisie_alarm_level:
  hidden: true
sensor.woonkamer__televisie_alarm_type:
  hidden: true
sensor.woonkamer__televisie_current:
  hidden: true
sensor.woonkamer__televisie_energy:
  hidden: true
sensor.woonkamer__televisie_exporting:
  hidden: true
sensor.woonkamer__televisie_interval:
  hidden: true
sensor.woonkamer__televisie_interval_2:
  hidden: true
sensor.woonkamer__televisie_interval_3:
  hidden: true
sensor.woonkamer__televisie_interval_4:
  hidden: true
sensor.woonkamer__televisie_power:
  friendly_name: "Televisie verbruik (w)"
  icon: "mdi:power-plug"
sensor.woonkamer__televisie_power_management:
  hidden: true
sensor.woonkamer__televisie_previous_reading:
  hidden: true
sensor.woonkamer__televisie_previous_reading_2:
  hidden: true
sensor.woonkamer__televisie_previous_reading_3:
  hidden: true
sensor.woonkamer__televisie_previous_reading_4:
  hidden: true
sensor.woonkamer__televisie_sourcenodeid:
  hidden: true
sensor.woonkamer__televisie_voltage:
  hidden: true
switch.woonkamer__televisie_switch:
  friendly_name: "Televisie"
  icon: "mdi:television-guide"
zwave.woonkamer__televisie:
  hidden: true

# Woonkamer PIR
binary_sensor.woonkamer__bewegingsmelder_sensor: # state: on/off
  name: "Beweging"
  icon: "mdi:run"
sensor.woonkamer__bewegingsmelder_alarm_level:
  hidden: true
sensor.woonkamer__bewegingsmelder_alarm_type:
  hidden: true
sensor.woonkamer__bewegingsmelder_burglar:
  hidden: true
sensor.woonkamer__bewegingsmelder_luminance:
  name: "Light"
  icon: "mdi:white-balance-sunny"
sensor.woonkamer__bewegingsmelder_sourcenodeid:
  hidden: true
zwave.woonkamer__bewegingsmelder:
  hidden: true

# Achtertuin
sensor.achtertuin__led_lampjes_energy:
  hidden: true
sensor.achtertuin__led_lampjes_power:
  hidden: true
sensor.achtertuin__led_lampjes_previous_reading:
  hidden: true
sensor.achtertuin__led_lampjes_previous_reading_2:
  hidden: true
switch.achtertuin__led_lampjes_switch:
  friendly_name: "Verlichting"
  icon: "mdi:led-outline"
zwave.achtertuin__led_lampjes:
  hidden: true

# Apparaten
# Vaatwasser
sensor.woonkamer__vaatwasser_energy:
  hidden: true
sensor.woonkamer__vaatwasser_power:
  friendly_name: "Vaatwasser verbruik"
  icon: "mdi:power-plug"
sensor.woonkamer__vaatwasser_previous_reading:
  hidden: true
sensor.woonkamer__vaatwasser_previous_reading_2:
  hidden: true
switch.woonkamer__vaatwasser_switch:
  friendly_name: "Vaatwasser"
  icon: "mdi:washing-machine"
zwave.woonkamer__vaatwasser:
  hidden: true

# Wasmachine
sensor.schuur__wasmachine_alarm_level:
  hidden: true
sensor.schuur__wasmachine_alarm_type:
  hidden: true
sensor.schuur__wasmachine_current:
  hidden: true
sensor.schuur__wasmachine_energy:
  hidden: true
sensor.schuur__wasmachine_exporting:
  hidden: true
sensor.schuur__wasmachine_interval:
  hidden: true
sensor.schuur__wasmachine_interval_2:
  hidden: true
sensor.schuur__wasmachine_interval_3:
  hidden: true
sensor.schuur__wasmachine_interval_4:
  hidden: true
sensor.schuur__wasmachine_power:
  friendly_name: "Wasmachine verbruik"
  icon: "mdi:power-plug"
sensor.schuur__wasmachine_power_management:
  hidden: true
sensor.schuur__wasmachine_previous_reading:
  hidden: true
sensor.schuur__wasmachine_previous_reading_2:
  hidden: true
sensor.schuur__wasmachine_previous_reading_3:
  hidden: true
sensor.schuur__wasmachine_previous_reading_4:
  hidden: true
sensor.schuur__wasmachine_sourcenodeid:
  hidden: true
sensor.schuur__wasmachine_voltage:
  hidden: true
switch.schuur__wasmachine_switch:
  friendly_name: "Wasmachine"
  icon: "mdi:washing-machine"
zwave.schuur__wasmachine:
  hidden: true

# Droger
sensor.schuur__droger_alarm_level:
  hidden: true
sensor.schuur__droger_alarm_type:
  hidden: true
sensor.schuur__droger_current:
  hidden: true
sensor.schuur__droger_energy:
  hidden: true
sensor.schuur__droger_exporting:
  hidden: true
sensor.schuur__droger_interval:
  hidden: true
sensor.schuur__droger_interval_2:
  hidden: true
sensor.schuur__droger_interval_3:
  hidden: true
sensor.schuur__droger_interval_4:
  hidden: true
sensor.schuur__droger_power:
  friendly_name: "Droger verbruik"
  icon: "mdi:power-plug"
sensor.schuur__droger_power_management:
  hidden: true
sensor.schuur__droger_previous_reading:
  hidden: true
sensor.schuur__droger_previous_reading_2:
  hidden: true
sensor.schuur__droger_previous_reading_3:
  hidden: true
sensor.schuur__droger_previous_reading_4:
  hidden: true
sensor.schuur__droger_sourcenodeid:
  hidden: true
sensor.schuur__droger_voltage:
  hidden: true
switch.schuur__droger_switch:
  friendly_name: "Droger"
  icon: "mdi:washing-machine"
zwave.schuur__droger:
  hidden: true

# Woonkamer MultiSensor
sensor.sensor_woonkamer__temperatuur:
  friendly_name: Temperatuur
sensor.sensor_woonkamer__luchtvochtigheid:
  friendly_name: Luchtvochtigheid
sensor.sensor_woonkamer__lichtsterkte:
  friendly_name: Lichtsterkte
sensor.sensor_woonkamer__bewegingsmelder:
  friendly_name: Bewegingsmelder
light.woonkamer__led:
  friendly_name: Lampje

sensor.sensor_slaapkamer_saar__temperatuur:
  friendly_name: Temperatuur
sensor.sensor_slaapkamer_saar__luchtvochtigheid:
  friendly_name: Luchtvochtigheid
sensor.sensor_slaapkamer_saar__lichtsterkte:
  friendly_name: Lichtsterkte
sensor.sensor_slaapkamer_saar__bewegingsmelder:
  friendly_name: Bewegingsmelder
light.slaapkamer_saar__led:
  friendly_name: Lampje

zwave.aeotec_zw090_zstick_gen5:
  hidden: true

binary_sensor.floorplan:
  custom_ui_state_card: floorplan
  config: !include floorplan.yaml