# Weer
sun.sun:
  hidden: true

# Woonkamer - Televisie
!secret livingroom_television_toggle:
  friendly_name: "Televisie"
  icon: "mdi:television-guide"
sensor.neo_coolcam_power_plug_12a_alarm_level_9_1:
  hidden: true
sensor.neo_coolcam_power_plug_12a_alarm_type_9_0:
  hidden: true
sensor.neo_coolcam_power_plug_12a_current_9_20:
  hidden: true
!secret livingroom_television_power_usage_total:
  friendly_name: "Televisie verbruik (kWh)"
  icon: "mdi:power-plug"
sensor.neo_coolcam_power_plug_12a_exporting_9_32:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_9_10:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_9_18:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_9_2:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_9_22:
  hidden: true
!secret livingroom_television_power_usage:
  friendly_name: "Televisie verbruik (w)"
  icon: "mdi:power-plug"
sensor.neo_coolcam_power_plug_12a_power_management_9_11:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_9_1:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_9_17:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_9_21:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_9_9:
  hidden: true
sensor.neo_coolcam_power_plug_12a_sourcenodeid_9_2:
  hidden: true
sensor.neo_coolcam_power_plug_12a_voltage_9_16:
  hidden: true

# Achtertuin
!secret backyard_light_toggle:
  friendly_name: "Led lampjes"
  icon: "mdi:led-outline"
sensor.greenwave_powernode_1_port_energy_3_0:
  hidden: true
sensor.greenwave_powernode_1_port_power_3_8:
  hidden: true
sensor.greenwave_powernode_1_port_previous_reading_3_1:
  hidden: true
sensor.greenwave_powernode_1_port_previous_reading_3_9:
  hidden: true

# Apparaten
# Vaatwasser
!secret dishwasher_power_toggle:
  friendly_name: "Vaatwasser"
  icon: "mdi:washing-machine"
sensor.greenwave_powernode_1_port_energy_2_0:
  hidden: true
!secret dishwasher_power_usage:
  friendly_name: "Vaatwasser verbruik"
  icon: "mdi:power-plug"
sensor.greenwave_powernode_1_port_previous_reading_2_1:
  hidden: true
sensor.greenwave_powernode_1_port_previous_reading_2_9:
  hidden: true

# Wasmachine
!secret shed_washingmachine_power_toggle:
  friendly_name: "Wasmachine"
  icon: "mdi:washing-machine"
!secret shed_washingmachine_power_usage:
  friendly_name: "Wasmachine verbruik"
  icon: "mdi:power-plug"
sensor.neo_coolcam_power_plug_12a_alarm_level_6_1:
  hidden: true
sensor.neo_coolcam_power_plug_12a_alarm_type_6_0:
  hidden: true
sensor.neo_coolcam_power_plug_12a_current_6_20:
  hidden: true
sensor.neo_coolcam_power_plug_12a_energy_6_0:
  hidden: true
sensor.neo_coolcam_power_plug_12a_exporting_6_32:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_6_10:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_6_18:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_6_2:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_6_22:
  hidden: true
sensor.neo_coolcam_power_plug_12a_power_management_6_11:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_6_1:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_6_17:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_6_21:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_6_9:
  hidden: true
sensor.neo_coolcam_power_plug_12a_sourcenodeid_6_2:
  hidden: true
sensor.neo_coolcam_power_plug_12a_voltage_6_16:
  hidden: true

# Droger
!secret dryer_power_toggle:
  friendly_name: "Droger"
  icon: "mdi:washing-machine"
!secret dryer_power_usage:
  friendly_name: "Droger verbruik"
  icon: "mdi:power-plug"
sensor.neo_coolcam_power_plug_12a_alarm_level_8_1:
  hidden: true
sensor.neo_coolcam_power_plug_12a_alarm_type_8_0:
  hidden: true
sensor.neo_coolcam_power_plug_12a_current_8_20:
  hidden: true
sensor.neo_coolcam_power_plug_12a_energy_8_0:
  hidden: true
sensor.neo_coolcam_power_plug_12a_exporting_8_32:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_8_10:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_8_18:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_8_2:
  hidden: true
sensor.neo_coolcam_power_plug_12a_interval_8_22:
  hidden: true
sensor.neo_coolcam_power_plug_12a_power_management_8_11:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_8_1:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_8_17:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_8_21:
  hidden: true
sensor.neo_coolcam_power_plug_12a_previous_reading_8_9:
  hidden: true
sensor.neo_coolcam_power_plug_12a_sourcenodeid_8_2:
  hidden: true
sensor.neo_coolcam_power_plug_12a_voltage_8_16:
  hidden: true

# Philips Hue
!secret livingroom_light:
  friendly_name: "Lamp Woonkamer"
  icon: "mdi:lightbulb-outline"
light.hue_color_lamp_2:
  friendly_name: "Lamp Bijkeuken"
  icon: "mdi:lightbulb-outline"