name: Plattegrond
image: /local/custom_ui/floorplan/floorplan.svg
stylesheet: /local/custom_ui/floorplan/floorplan.css
warnings: 
date_format: DD-MMM-YYYY
# pan_zoom:
# hide_app_toolbar
# last_motion_entity: sensor.template_last_motion
# last_motion_class: last-motion

groups:
  - name: temperature
    entities:
      - sensor.sensor_kantoor__temperatuur
      - sensor.sensor_slaapkamer_saar__temperatuur
    text_template: '${entity.state ? entity.state + "°C": "-"}'
    # class_template: 'return "static-temp";'

  - name: humidity
    entities:
      - sensor.sensor_kantoor__luchtvochtigheid
      - sensor.sensor_slaapkamer_saar__luchtvochtigheid
    text_template: '${entity.state ? entity.state + "%": "-"}'
    # class_template: 'return "static-temp";'

  - name: Lights
    entities:
      - light.hue_color_lamp_1
    states:
      - state: 'on'
        class: 'light-on'
      - state: 'off'
        class: 'light-off'
    action:
      service: toggle

    # action:
    #   domain: homeassistant   # This optional parameter allows you to use other services such as homeassistant.toggle like here.
    #   service: toggle
  # - name: Switches
  #   entities:
  #       - switch.doorbell
  #   states:
  #     - state: 'on'
  #       class: 'doorbell-on'
  #     - state: 'off'
  #       class: 'doorbell-off'

  # - name: Alarm Panel
  #   entities:
  #       - alarm_control_panel.alarm
  #   states:
  #     - state: 'armed_away'
  #       class: 'alarm-armed'
  #     - state: 'armed_home'
  #       class: 'alarm-armed'
  #     - state: 'disarmed'
  #       class: 'alarm-disarmed'

  # - name: Binary sensors
  #   entities:
  #     - binary_sensor.front_hallway
  #     - binary_sensor.kitchen
  #     - binary_sensor.master_bedroom
  #     - binary_sensor.theatre_room
  #   states:
  #     - state: 'off'
  #       class: 'info-light'
  #     - state: 'on'
  #       class: 'warning-light'
  #   state_transitions:
  #     - name: On to off
  #       from_state: 'on'
  #       to_state: 'off'
  #       duration: 10

  # - name: Cameras
  #   entities:
  #     - camera.hallway
  #     - camera.driveway
  #     - camera.front_door
  #     - camera.backyard
  #   states:
  #     - state: 'idle'
  #       class: 'camera-idle'
