name: Demo Floorplan
image: /local/custom_ui/floorplan/floorplan.svg
stylesheet: /local/custom_ui/floorplan/floorplan.css

# last_motion_entity: sensor.template_last_motion
# last_motion_class: last-motion

groups:
  - name: Sensors
    entities:
        - sensor.sensor_woonkamer__temperatuur
    text_template: '${entity.state ? entity.state : "unknown"}'
    class_template: '
      var temp = parseFloat(entity.state.replace("°", ""));
      if (temp < 10)
        return "temp-low";
      else if (temp < 22)
        return "temp-medium";
      else
        return "temp-high";
      '
  - name: Lights
    entities:
        - light.hue_color_lamp_1
        # - light.living_room
        # - light.patio
    states:
      - state: 'on'
        class: 'light-on'
      - state: 'off'
        class: 'light-off'

  # - name: Switches
  #   entities:
  #       - switch.doorbell
  #   states:
  #     - state: 'on'
  #       class: 'doorbell-on'
  #     - state: 'off'
  #       class: 'doorbell-off'

  # - name: Alarm Panel
  #   entities:
  #       - alarm_control_panel.alarm
  #   states:
  #     - state: 'armed_away'
  #       class: 'alarm-armed'
  #     - state: 'armed_home'
  #       class: 'alarm-armed'
  #     - state: 'disarmed'
  #       class: 'alarm-disarmed'

  # - name: Binary sensors
  #   entities:
  #     - binary_sensor.front_hallway
  #     - binary_sensor.kitchen
  #     - binary_sensor.master_bedroom
  #     - binary_sensor.theatre_room
  #   states:
  #     - state: 'off'
  #       class: 'info-light'
  #     - state: 'on'
  #       class: 'warning-light'
  #   state_transitions:
  #     - name: On to off
  #       from_state: 'on'
  #       to_state: 'off'
  #       duration: 10

  # - name: Cameras
  #   entities:
  #     - camera.hallway
  #     - camera.driveway
  #     - camera.front_door
  #     - camera.backyard
  #   states:
  #     - state: 'idle'
  #       class: 'camera-idle'
