hue_scenes:
  name: Scenes
  options:
    - '-'
    - 'Ontspannen'
    - 'Lezen'
    - 'Energie'
    - 'Concentreren'
    - 'Savanne zonsondergang'
    - 'Tropische schemering'
    - 'Arctische dageraad'
    - 'Lentebloesem'
    - 'Helder'
    - 'Gedimd'
    - 'Nachtlampje'
  icon: mdi:creation

hue_switch:
  name: Hue Tap Button
  options:
    - '-'
    - 20 # links boven
    - 21 # links onder
    - 22 # rechts onder
    - 23 # rechts boven