washingmachine_busy:
  name: Wasmachine bezig
  initial: off
  icon: "mdi:washing-machine"

dryer_busy:
  name: Droger bezig
  initial: off
  icon: "mdi:washing-machine"

dishwasher_busy:
  name: Vaatwasser bezig
  initial: off
  icon: "mdi:washing-machine"

play_saskia_pick_up_sound:
  name: Saskia neem je telefoon op
  initial: off
  icon: "mdi:voice"

trash_moved:
  name: Trash has been moved
  initial: 'off'
  icon: "mdi:delete-empty"

trash_reminder:
  name: Trash reminder enabled
  initial: 'on'

occupancy_simulator:
  name: Occupancy Simulator
  initial: 'on'

enable_vacation:
  name: Vacation mode
  initial: 'off'

babysitter:
  name: Oppas
  initial: 'off'
  icon: "mdi:account-child"