- platform: mqtt_json
  name: "Sensor 01 - LED"
  state_topic: "bruh/sensornode1"
  command_topic: "bruh/sensornode1/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0

- platform: mqtt_json
  name: "Sensor 02 - LED"
  state_topic: "bruh/sensornode2"
  command_topic: "bruh/sensornode2/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0