occupancy_simulator:
  sequence:
    - delay: '00:{{ range(1,20) | random | int }}:00'

    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 255
    - service: light.turn_on
      data:
        entity_id: light.keuken
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: switch.turn_on
      data:
        entity_id: switch.tv_switch

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_on
      data:
        entity_id: light.eetkamer
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.keuken

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 200

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.eetkamer

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: homeassistant.turn_on
      data:
        entity_id: light.keuken
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.keuken

    - delay: '00:{{ range(10,40) | random | int }}:00'

    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_on
      data:
        entity_id: light.eetkamer
        brightness: 255

    - service: light.turn_on
      data:
        entity_id: light.kantoor
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.keuken

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_on
      data:
        entity_id: light.woonkamer
        brightness: 200

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.eetkamer

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: homeassistant.turn_on
      data:
        entity_id: light.keuken
        brightness: 255

    - delay: '00:0{{ range(9) | random | int }}:{{ range(10,58) | random | int }}'

    - service: light.turn_off
      data:
        entity_id: light.keuken

    - service: switch.turn_off
      data:
        entity_id: switch.tv_switch

    - service: script.turn_on
      data:
        entity_id: script.light_loop

occupancy_simulator_loop:
  sequence:
    - delay:
        seconds: 1
    - service: script.turn_on
      data:
        entity_id: script.occupancy_simulator

alarm_flash:
  alias: Knipper wekker lampje
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.multisensor04_light
    - delay:
        seconds: 0.5 # time for flash light on
    - service: light.turn_off
      data:
        entity_id: light.multisensor04_light
    - service: script.turn_on
      data:
        entity_id: script.alarm_flash_loop

alarm_flash_loop:
  alias: Knipper wekker lampje - loop
  sequence:
    - delay:
        seconds: 0.5 # time for flash light off
    - service: script.turn_on
      data:
        entity_id: script.alarm_flash
