# Based on https://github.com/seangreen2/slate_theme
slate:
  # Main colors
  primary-color: '#999'
  accent-color: '#ff0000'
  dark-primary-color: '#e0e1e1'
  light-primary-color: '#262b2c'
  # Text colors
  primary-text-color: '#e0e1e1'
  text-primary-color: 'var(--primary-text-color)'
  secondary-text-color: 'rgba(224, 225, 225, 0.3)'
  disabled-text-color: '#777777'
  label-badge-border-color: 'green'
  # Sidebar
  sidebar-icon-color: '#9e9e9e'
  # Background colors
  primary-background-color: '#222627'
  secondary-background-color: '#434b4d'
  divider-color: 'rgba(0, 0, 0, .12)'
  table-row-background-color: '#292929'
  table-row-alternative-background-color: '#292929'
  # Nav Menu
  paper-listbox-color: '#CCC'
  paper-listbox-background-color: '#222627'
  paper-grey-50: 'var(--primary-text-color)'
  paper-grey-200: '#222222'
  # Paper card
  paper-card-header-color: '#252b2d'
  paper-card-background-color: '#222627'
  paper-dialog-background-color: '#2d3538'
  paper-item-icon-color: '#9da0a2'
  paper-item-icon-active-color: '#3182b7'
  paper-item-icon_-_color: 'green'
  paper-item-selected_-_background-color: '#ff0000'
  paper-tabs-selection-bar-color: 'green'
  # Labels
  label-badge-red: 'var(--primary-color)'
  label-badge-text-color: 'var(--primary-text-color)'
  label-badge-background-color: '#222222'
  # Switches update
  switch-checked-color: '#7a7d7f'
  switch-unchecked-button-color: '#3b4041'
  switch-unchecked-track-color: '#0c0d0d'
  # paper-toggle-button-checked-bar-color: '#009FFF'
  # Sliders
  paper-slider-knob-color: '#a4abb1'
  paper-slider-knob-start-color: '#a4abb1'
  paper-slider-pin-color: '#626a6f'
  paper-slider-active-color: '#626a6f'
  paper-slider-container-color: '#202020'
  paper-slider-secondary-color: 'var(--secondary-background-color)'
  paper-slider-disabled-active-color: 'var(--disabled-text-color)'
  paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
  #paper-slider-height: '3px'
  # Google colors
  google-red-500: '#bf3838'
  google-green-500: '#5b8d47'
  # Changes to fix history/logbook menus
  lumo-primary-text-color: '#2980b9'
  lumo-secondary-text-color: '#2980b9'
  lumo-primary-color: '#2980b9'
  # Calendar day numbers
  lumo-body-text-color: '#e0e1e1'
  # Calendar/Date-Picker Background
  lumo-base-color: '#222222'
  # Month/Year header
  lumo-header-text-color: 'var(--lumo-body-text-color)'
  # DayOfWeek Header
  lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
  lumo-shade: '#222222'
  lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
  lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
  lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
  lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
  lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
  lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
  lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
  lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
  lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
  lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
  lumo-tint-5pct: '#222222'
  # fix for device configuration screen
  card-background-color: "var(--paper-card-background-color)"
  # mini-media-player
  mini-media-player-base-color: '#d7d7d6'
  mini-media-player-accent-color: '#d7d7d6'
  mini-media-player-icon-color: '#9e9e9e'
  mini-media-player-overlay-color: 'rgba(0,0,0,0)'
  mini-media-player-overlay-color-stop: '100%'
  mini-media-player-overlay-base-color: '#d7d7d6'
  mini-media-player-overlay-accent-color: '#d7d7d6'
  mini-media-player-media-cover-info-color: '#d7d7d6'
  mini-media-player-background-opacity: '0'
  mini-media-player-artwork-opacity: '1'
  mini-media-player-progress-height: '5px'
  mini-media-player-scale: '1.14'
  # popup-backdrop-filter
  iron-overlay-backdrop-filter: 'blur(15px)'
  iron-overlay-backdrop-background-color: 'rgba(0,0,0,.6)'
  iron-overlay-backdrop-opacity: '1'
  # barcard
  bar-card-border-radius: '0.3em'