title: Lampen
panel: true
background: >-
  right/auto linear-gradient(23deg, rgba(211,211,211,1) 0%,
  rgba(223,223,223,1) 34%, rgba(255,255,255,1) 100%)
cards:
  - cards:
      - cards:
          - cards:
              - template: sjors_button
                type: 'custom:decluttering-card'
                variables:
                  - entity: light.woonkamer_lamp
                  - name: Lamp
                  - hold_action:
                      action: more-info
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.woonkamer_spot_1
                      - name: Spot 1
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.woonkamer_spot_3
                      - name: Spot 3
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.woonkamer_spot_2
                      - name: Spot 2
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.woonkamer_spot_4
                      - name: Spot 4
                      - hold_action:
                          action: more-info
                type: vertical-stack
            type: horizontal-stack
        title: Woonkamer
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.keuken_spot_1
                      - name: Spot 1
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.keuken_spot_4
                      - name: Spot 4
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.keuken_spot_2
                      - name: Spot 2
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.keuken_spot_5
                      - name: Spot 5
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.keuken_spot_3
                      - name: Spot 3
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.keuken_spot_6
                      - name: Spot 6
                      - hold_action:
                          action: more-info
                type: vertical-stack
            type: horizontal-stack
        title: Keuken
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.eetkamer_tafel_lamp_1
                      - name: Lamp 1
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.eetkamer_spot_1
                      - name: Spot 1
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.eetkamer_tafel_lamp_2
                      - name: Lamp 2
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.eetkamer_spot_2
                      - name: Spot 2
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.eetkamer_tafel_lamp_3
                      - name: Lamp 3
                      - hold_action:
                          action: more-info
                type: vertical-stack
            type: horizontal-stack
        title: Eetkamer
        type: 'custom:vertical-stack-in-card'
      - break
      - cards:
          - cards:
              - template: sjors_button
                type: 'custom:decluttering-card'
                variables:
                  - entity: light.slaapkamer_saar_leeslampje
                  - name: Leeslampje
                  - hold_action:
                      action: more-info
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.slaapkamer_saar_spot_1
                      - name: Spot 1
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.slaapkamer_saar_spot_3
                      - name: Spot 3
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.slaapkamer_saar_spot_2
                      - name: Spot 2
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.slaapkamer_saar_spot_4
                      - name: Spot 4
                      - hold_action:
                          action: more-info
                type: vertical-stack
            type: horizontal-stack
        title: Slaapkamer Saar
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.nachtlamp_sjors
                      - name: Sjors
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.nachtlamp_saskia
                      - name: Saskia
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.grote_slaapkamer_spot_1
                      - name: Spot 1
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.grote_slaapkamer_spot_4
                      - name: Spot 4
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.grote_slaapkamer_spot_2
                      - name: Spot 2
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.grote_slaapkamer_spot_3
                      - name: Spot 3
                      - hold_action:
                          action: more-info
                type: vertical-stack
            type: horizontal-stack
        title: Grote slaapkamer
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.kantoor_spot_1
                      - name: Spot 1
                      - hold_action:
                          action: more-info
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.kantoor_spot_4
                      - name: Spot 4
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.kantoor_spot_2
                      - name: Spot 2
                      - hold_action:
                          action: more-info
                type: vertical-stack
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: light.kantoor_spot_3
                      - name: Spot 3
                      - hold_action:
                          action: more-info
                type: vertical-stack
            type: horizontal-stack
        title: Kantoor
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - template: sjors_button
                type: 'custom:decluttering-card'
                variables:
                  - entity: light.overloop_spot_1
                  - name: Spot 1
                  - hold_action:
                      action: more-info
              - template: sjors_button
                type: 'custom:decluttering-card'
                variables:
                  - entity: light.overloop_spot_2
                  - name: Spot 2
                  - hold_action:
                      action: more-info
            type: horizontal-stack
        title: Overloop
        type: 'custom:vertical-stack-in-card'
    layout: horizontal
    type: 'custom:layout-card'