panel: true
title: Overig
background: >-
  right/auto linear-gradient(23deg, rgba(211,211,211,1) 0%,
  rgba(223,223,223,1) 34%, rgba(255,255,255,1) 100%)
cards:
  - cards:
      - cards:
          - cards:
              - cards:
                  - template: sjors_button
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: input_boolean.play_saskia_pick_up_sound
                      - name: Saskia neem je telefoon op
                      - state:
                          - color: '#87c087'
                            icon: 'mdi:bullhorn'
                            value: 'on'
                          - color: '#BAC0C6'
                            icon: 'mdi:bullhorn-outline'
                            value: 'off'
                          - color: '#ff0000'
                            icon: 'mdi:bullhorn-outline'
                            value: unavailable
                type: horizontal-stack
              - cards:
                  - entity: media_player.google_hub
                    name: Woonkamer
                    tts:
                      platform: google
                    type: 'custom:mini-media-player'
                  - entity: media_player.google_home_mini
                    name: Slaapkamer
                    tts:
                      platform: google
                    type: 'custom:mini-media-player'
                  - entity: media_player.google_home
                    name: Kantoor
                    tts:
                      platform: google
                    type: 'custom:mini-media-player'
                type: vertical-stack
            type: vertical-stack
        title: Intercom
        type: 'custom:vertical-stack-in-card'
      - break
      - entities:
          - entity: input_boolean.occupancy_simulator
            icon: 'mdi:run-fast'
          - entity: input_boolean.enable_vacation
            icon: 'mdi:beach'
        show_header_toggle: false
        type: entities
      - entities:
          - entity: input_boolean.alarm_enabled
          - entity: input_number.alarm_hour
          - entity: input_number.alarm_minutes
        show_header_toggle: false
        title: Wekker
        type: entities
    layout: vertical
    type: 'custom:layout-card'