title: Sensoren
panel: true
background: >-
  right/auto linear-gradient(23deg, rgba(211,211,211,1) 0%,
  rgba(223,223,223,1) 34%, rgba(255,255,255,1) 100%)
cards:
  - cards:
      - cards:
          - cards:
              - template: sjors_mini_graph_left
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.multisensor01_temperature
              - template: sjors_mini_graph_right
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.multisensor01_humidity
            type: horizontal-stack
        title: Woonkamer
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - template: sjors_mini_graph_left
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.multisensor02_temperature
              - template: sjors_mini_graph_right
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.multisensor02_humidity
            type: horizontal-stack
        title: Zolder
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - template: sjors_mini_graph_left
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.multisensor03_temperature
              - template: sjors_mini_graph_right
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.multisensor03_humidity
            type: horizontal-stack
        title: Buiten
        type: 'custom:vertical-stack-in-card'
      - break
      - cards:
          - decimals: 4
            entities:
              - sensor.power_consumption
            height: 98
            hour24: true
            hours_to_show: 0.5
            line_color: '#D84315'
            name: Stroom verbruik
            points_per_hour: 120
            show:
              graph: bar
              icon: false
              name: false
            type: 'custom:mini-graph-card'
        title: Stroom verbruik
        type: 'custom:vertical-stack-in-card'
      - cards:
          - decimals: 4
            entities:
              - sensor.hourly_gas_consumption
            height: 98
            hour24: true
            hours_to_show: 0.5
            line_color: '#FDD835'
            name: Stroom verbruik
            points_per_hour: 120
            show:
              graph: bar
              icon: false
              name: false
            type: 'custom:mini-graph-card'
        title: Gas verbruik
        type: 'custom:vertical-stack-in-card'
      - break
      - cards:
          - template: sjors_mini_graph_basic
            type: 'custom:decluttering-card'
            variables:
              - entity: sensor.energy_01_wattage
              - line_color: '#D84315'
              - name: Koelkast
          - template: sjors_mini_graph_basic
            type: 'custom:decluttering-card'
            variables:
              - entity: sensor.energy_02_wattage
              - line_color: '#D84315'
              - name: NAS
        type: horizontal-stack
      - cards:
          - template: sjors_mini_graph_basic
            type: 'custom:decluttering-card'
            variables:
              - entity: sensor.energy_03_wattage
              - line_color: '#D84315'
              - name: Droger
          - template: sjors_mini_graph_basic
            type: 'custom:decluttering-card'
            variables:
              - entity: sensor.energy_04_wattage
              - line_color: '#D84315'
              - name: Wasmachine
        type: horizontal-stack
      - cards:
          - template: sjors_mini_graph_basic
            type: 'custom:decluttering-card'
            variables:
              - entity: sensor.zwave_energy_01_wattage
              - line_color: '#D84315'
              - name: Kantoor
          - template: sjors_mini_graph_basic
            type: 'custom:decluttering-card'
            variables:
              - entity: sensor.zwave_energy_03_wattage
              - line_color: '#D84315'
              - name: Vaatwasser
        type: horizontal-stack
      - cards:
          - template: sjors_mini_graph_basic
            type: 'custom:decluttering-card'
            variables:
              - entity: sensor.zwave_energy_04_wattage
              - line_color: '#D84315'
              - name: TV
        type: horizontal-stack
    layout: vertical
    type: 'custom:layout-card'