panel: true
title: Video
background: >-
  right/auto linear-gradient(23deg, rgba(211,211,211,1) 0%,
  rgba(223,223,223,1) 34%, rgba(255,255,255,1) 100%)
cards:
  - cards:
      - aspect_ratio: 56.25
        camera_image: camera.generic_camera
        camera_view: live
        entities: []
        title: Voordeur
        type: picture-glance
    layout: vertical
    type: 'custom:layout-card'